-- Create artist_profiles table
CREATE TABLE IF NOT EXISTS artist_profiles (
	id INT AUTO_INCREMENT PRIMARY KEY,
	user_id INT NOT NULL UNIQUE,
	bio TEXT NULL,
	portfolio_url VARCHAR(255) NULL,
	socials_json JSON NULL,
	location VARCHAR(255) NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);





